const ADD_TO_CART = `ADD_TO_CART`;
const REMOVE_FROM_CART = `REMOVE_FROM_CART`;
const ADD_TO_CART_BY_INCREMENT = `ADD_TO_CART_BY_INCREMENT`;
const REMOVE_FROM_CART_BY_DECREMENT = `REMOVE_FROM_CART_BY_DECREMENT`;

export const CART_CONSTANTS = {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  ADD_TO_CART_BY_INCREMENT,
  REMOVE_FROM_CART_BY_DECREMENT
};
